services:
  server:
    build: .
    image: bew111/promptcachedb
    
    ports:
      - "8000:8000"

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        - action: rebuild
          path: ./pyproject.toml